version: 2
updates:
  # Maintain dependencies for npm (JavaScript & TypeScript)
  - package-ecosystem: "npm"
    directory: "/"                # Location of package.json
    schedule:
      interval: "weekly"          # Options: "daily", "weekly", "monthly"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps"
    labels:
      - "dependencies"
      - "npm"

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "ci"
    labels:
      - "dependencies"
      - "github-actions"
