# ============================================================================
# GIVC Platform - pnpm Workspace Configuration
# ============================================================================
# This file defines the monorepo workspace structure for the GIVC platform
# and its related packages in the nphies-rcm ecosystem.
# ============================================================================

packages:
  # Main GIVC Platform Application
  - '.'
  
  # Future Package Structure (when migrating to parent nphies-rcm directory)
  # Uncomment these when setting up the monorepo in the parent directory:
  
  # - 'packages/*'
  # - 'packages/givc-platform'
  # - 'packages/nphies-core'
  # - 'packages/shared-types'
  # - 'packages/shared-config'
  # - 'packages/shared-services'
  # - 'packages/medical-agents'
  # - 'packages/medivault-core'
  
  # Example apps (for testing and documentation)
  # - 'apps/*'
  # - 'apps/docs'
  # - 'apps/playground'

# ============================================================================
# Workspace Protocol
# ============================================================================
# Use workspace protocol to reference internal packages:
# "dependencies": {
#   "@givc/shared-types": "workspace:*",
#   "@nphies/core": "workspace:*"
# }
# ============================================================================

# ============================================================================
# Migration Notes:
# ============================================================================
# Phase 1 (Current): Single package in GIVC directory
# Phase 2 (Planned): Move to parent nphies-rcm directory structure
# Phase 3 (Future): Full monorepo with shared packages
#
# When migrating:
# 1. Move GIVC to nphies-rcm/packages/givc-platform/
# 2. Create shared packages in nphies-rcm/packages/
# 3. Update this file to include all package paths
# 4. Update package.json dependencies to use workspace protocol
# 5. Run 'pnpm install' to update workspace links
# ============================================================================
