app:
  name: BrainSAIT-NPHIES-GIVC-Integration
  version: 2.0.0
  description: Advanced AI-Powered Healthcare Integration Platform with NPHIES and GIVC
  platform_url: https://4d31266d.givc-platform-static.pages.dev/

# Al Hayat National Hospital Configuration
hospital:
  name: Al Hayat National Hospital
  nphies_id: "10000000000988"
  chi_id: "1048"
  license_number: "7000911508"
  ftp_host: "172.25.11.15"
  
branches:
  - id: riyadh
    name: Riyadh
    code: RYD
    enabled: true
    ip_address: "128.1.1.185"
  - id: madinah
    name: Madinah
    code: MDN
    enabled: true
    ip_address: "172.25.11.26"
  - id: unaizah
    name: Unaizah
    code: UNZ
    enabled: true
    ip_address: "10.0.100.105"
  - id: khamis
    name: Khamis Mushait
    code: KMS
    enabled: true
    ip_address: "172.30.0.77"
  - id: jizan
    name: Jizan
    code: JZN
    enabled: true
    ip_address: "172.17.4.84"
  - id: abha
    name: Abha
    code: ABH
    enabled: true
    ip_address: "172.19.1.1"

# NPHIES Integration Configuration
nphies:
  name: National Platform for Health Insurance Exchange Services
  enabled: true
  
  # Environment Configuration
  environments:
    production:
      name: Production
      base_url: https://HSB.nphies.sa
      enabled: true
      require_certificate: true
    sandbox:
      name: Sandbox
      base_url: https://sandbox.nphies.sa
      enabled: true
      require_certificate: false
    conformance:
      name: Conformance Testing
      base_url: https://conformance.nphies.sa
      enabled: true
      require_certificate: false
  
  # NPHIES Endpoints
  endpoints:
    auth:
      token: /auth/realms/sehaticoreprod/protocol/openid-connect/token
      login: /auth/realms/sehaticoreprod/protocol/openid-connect/auth
    eligibility:
      check: /eligibility/v1/check
      inquiry: /eligibility/v1/inquiry
    prior_authorization:
      create: /priorauth/v1/create
      status: /priorauth/v1/status
      cancel: /priorauth/v1/cancel
    claims:
      submit: /claim/v1/submit
      status: /claim/v1/status
      cancel: /claim/v1/cancel
      resubmit: /claim/v1/resubmit
    communication:
      send: /communication/v1/send
      receive: /communication/v1/receive
    poll:
      status: /poll/v1/status
      
  # Hospital Configuration
  hospital_config:
    nphies_id: "10000000000988"
    chi_id: "1048"
    organization_license: "7000911508"
    
  # Authentication
  authentication:
    method: certificate
    client_id: community
    realm: sehaticoreprod
    certificate_required: true
    certificate_path: ./certificates/nphies_production.pem
    private_key_path: ./certificates/nphies_production_key.pem
    
  # Transaction Settings
  transaction:
    timeout: 30
    retry_attempts: 3
    batch_size: 100
    max_concurrent: 10
    
  # Monitoring
  monitoring:
    real_time: true
    uptime_target: 99.9
    alert_threshold: 95.0

# GIVC Platform Integration
givc:
  name: GIVC Healthcare Platform
  enabled: true
  platform_url: https://4d31266d.givc-platform-static.pages.dev/
  
  endpoints:
    enhanced_nphies: /nphies-enhanced
    admin_dashboard: /nphies-admin
    api_gateway: /api
    communication: /communication
    
  features:
    ai_powered_processing: true
    real_time_integration: true
    enterprise_security: true
    mobile_first_design: true
    intelligent_validation: true
    automated_error_detection: true
    smart_form_completion: true
    
  # BrainSAIT Ultrathink AI
  ultrathink:
    enabled: true
    ai_validation: true
    smart_completion: true
    error_prediction: true
    claim_optimization: true

# Insurance Provider - TAWUNIYA
tawuniya:
  name: TAWUNIYA Medical Insurance
  enabled: true
  license: "7000911508"
  group_code: "1096"
  contact_person: "MOHAMMED SALEH"
  
  policies:
    - name: BALSAM GOLD 1
      code: BALSAM_GOLD_1
      enabled: true
    - name: BALSAM GOLD 2
      code: BALSAM_GOLD_2
      enabled: true
    - name: BALSAM GOLD 3
      code: BALSAM_GOLD_3
      enabled: true
    - name: BALSAM GOLD 4
      code: BALSAM_GOLD_4
      enabled: true
    - name: BALSAM GOLD 5
      code: BALSAM_GOLD_5
      enabled: true
    - name: BALSAM GOLD 6
      code: BALSAM_GOLD_6
      enabled: true
    - name: BALSAM GOLD 7
      code: BALSAM_GOLD_7
      enabled: true
    - name: BALSAM GOLD 8
      code: BALSAM_GOLD_8
      enabled: true

# NCCI Referral System
ncci:
  name: NCCI Referral System
  enabled: true
  account: "INS-809"
  license: "7000911508"
  referral_management: true

# Portal Configurations (Legacy)
portals:
  oases:
    name: OASES Plus
    timeout: 30
    retry_attempts: 3
    session_pool_size: 5
    branches:
      riyadh:
        url: https://128.1.1.185/prod/faces/Home
        login_endpoint: /faces/Login.jsf
        verify_ssl: false
      madinah:
        url: http://172.25.11.26/Oasis/faces/Login.jsf
        login_endpoint: /faces/Login.jsf
        verify_ssl: false
      unaizah:
        url: http://10.0.100.105/prod/faces/Login.jsf
        login_endpoint: /faces/Login.jsf
        verify_ssl: false
      khamis:
        url: http://172.30.0.77/prod/faces/Login.jsf
        login_endpoint: /faces/Login.jsf
        verify_ssl: false
      jizan:
        url: http://172.17.4.84/prod/faces/Login.jsf
        login_endpoint: /faces/Login.jsf
        verify_ssl: false
      abha:
        url: http://172.19.1.1/Oasis/faces/Home
        login_endpoint: /faces/Login.jsf
        verify_ssl: false

  moh:
    name: Ministry of Health Portal
    timeout: 30
    retry_attempts: 3
    approval_portal:
      enabled: true
    claims_portal:
      url: https://e-claims.globemedsaudi.com/login.html
      enabled: true
    branches:
      riyadh:
        username: C1120
        approval_user: MOH-C1120
      khamis:
        username: C1437
        approval_user: C1437HN-MH
      unaizah:
        username: C1287
        approval_user: MOH-C1287
      jizan:
        username: H513881
        approval_user: MH-H513881
      abha:
        username: H563301
        approval_user: MH-H563301
      madinah:
        username: C1531
        approval_user: C1531

  jisr:
    name: Jisr Platform
    timeout: 30
    retry_attempts: 3
    branches:
      madinah:
        username: dhq.jisr
      jizan:
        username: hanhj.jisr
      khamis:
        username: hnh.jisr
      riyadh:
        username: mws.jisr
      unaizah:
        username: waf.jisr
      abha:
        username: hnh.abha

  bupa:
    name: Bupa Arabia
    timeout: 30
    retry_attempts: 3
    branches:
      riyadh:
        username: rcm2024
      jizan:
        username: HNHRejection
      madinah:
        username: rcm.rejection
      unaizah:
        username: Claims_qassim
        alternate_username: u_3392
      khamis:
        username: RCM-REJECTION

# Remote Access Configuration
remote_access:
  jizan:
    ip: "172.17.4.202"
    username: "hayathospital\\Inma4"
    port: 3389
  madinah:
    ip: "172.25.11.70"
    username: "HNHMadinah.com\\inma4"
    port: 3389
  khamis:
    ip: "172.18.1.105"
    username: "hnhassir\\inma4"
    port: 3389
  unaizah:
    ip: "10.0.99.10"
    username: ".\\inma4"
    port: 3389

# Monitoring and Analytics
monitoring:
  enabled: true
  health_check_interval: 60
  metrics_enabled: true
  alert_on_failure: true
  max_consecutive_failures: 3
  statistics:
    insurance_providers: 150
    healthcare_facilities: 500
    active_transactions_daily: 10000
    target_uptime: 99.9
    
# Security Configuration
security:
  certificate_authentication: true
  encrypted_communications: true
  saudi_healthcare_compliance: true
  hipaa_compliant: true
  data_encryption: AES-256
  tls_version: "1.3"
  
# Integration Settings
integration:
  nphies:
    enabled: true
    environment: production
    real_time_monitoring: true
    ai_validation: true
  givc:
    enabled: true
    ultrathink_ai: true
    smart_forms: true
  brainsait:
    enabled: true
    ai_processing: true
    claim_optimization: true
    error_detection: true
