name = "givc"
main = "workers/router.js"
compatibility_date = "2023-11-01"

# Pages configuration - Use root directory for static HTML site
pages_build_output_dir = "."

# If you want to build the frontend subdirectory instead, use:
# pages_build_output_dir = "dist"
# pages_build_command = "npm run build"

# Environment variables for Pages
[vars]
ENVIRONMENT = "production"
HIPAA_COMPLIANCE_LEVEL = "strict"
RCM_ACCREDITATION = "enabled"

# D1 Database Bindings
[[d1_databases]]
binding = "DB"
database_name = "givc-healthcare-prod"
database_id = "" # Will be set during deployment

[[d1_databases]]
binding = "HEALTHCARE_DB"
database_name = "givc-healthcare-prod"
database_id = "" # Will be set during deployment

# KV Namespace Bindings
[[kv_namespaces]]
binding = "MEDICAL_METADATA"
id = "" # Will be set during deployment

[[kv_namespaces]]
binding = "AUDIT_LOGS"
id = "" # Will be set during deployment

# R2 Bucket Bindings
[[r2_buckets]]
binding = "MEDICAL_FILES"
bucket_name = "givc-medical-files"

# Secrets (Set via GitHub Actions or wrangler secret put)
# Required secrets:
# - JWT_SECRET: Secret key for JWT signing
# - ENCRYPTION_KEY: Master encryption key for AES-256-GCM
# - CLOUDFLARE_API_TOKEN: API token for Cloudflare access
# - CLOUDFLARE_ACCOUNT_ID: Account ID

# Workers AI Binding
[ai]
binding = "AI"

# Queue Binding (for async processing)
[[queues.producers]]
binding = "PROCESSING_QUEUE"
queue = "medical-processing-queue"

# Durable Objects (for rate limiting)
[[durable_objects.bindings]]
name = "RATE_LIMITER"
class_name = "RateLimiter"
script_name = "givc"

# Limits and Resources
[limits]
cpu_ms = 50

